#!/usr/bin/env python3
"""Regenerate docs/takendocs.md from the installed `taken` CLI.

Usage (from the repo root):
    python3 scripts/gen_cli_reference.py

`taken` must be importable/installable in the current environment
(e.g. `uv pip install .` first). The script runs `taken --help`,
reads the exit-code contract from taken.cli, and writes the page.

The generated page is committed to the repo. It appears in the site
navigation as "takendocs" and is intentionally not linked from the
README homepage.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "takendocs.md"

EXIT_CODE_BLURBS = {
    0: "GO: the issue looks open for contributions.",
    1: "TAKEN: someone already appears to be working on it.",
    2: "CAUTION: mixed signals; read the printed reasons before volunteering.",
    3: "Hard failure: usage error, API failure, or unexpected error. "
    "Nothing was decided; no verdict was recorded.",
}


def main() -> int:
    proc = subprocess.run(["taken", "--help"], capture_output=True, text=True, check=False)
    if proc.returncode != 0 or not proc.stdout.strip():
        print("error: `taken --help` did not produce output", file=sys.stderr)
        print(proc.stderr, file=sys.stderr)
        return 1

    try:
        from taken.cli import EXIT_CODES  # noqa: PLC0415
    except Exception as exc:  # fail loudly rather than document wrong codes
        print(f"error: could not import EXIT_CODES from taken.cli: {exc}", file=sys.stderr)
        return 1

    rows = []
    for _verdict, code in sorted(EXIT_CODES.items(), key=lambda kv: kv[1]):
        blurb = EXIT_CODE_BLURBS.get(code, "")
        rows.append(f"| `{code}` | {blurb} |")
    # 3 is the hard-failure convention used across main(); it is not in
    # EXIT_CODES because it is not a verdict.
    rows.append(f"| `3` | {EXIT_CODE_BLURBS[3]} |")

    page = f"""<!-- AUTO-GENERATED by scripts/gen_cli_reference.py — do not edit by hand. -->

# takendocs

Auto-generated CLI reference for `taken`. Regenerate with
`python3 scripts/gen_cli_reference.py` after CLI changes.

## Usage

```text
{proc.stdout.rstrip()}
```

## Exit codes

| Code | Meaning |
|------|---------|
{chr(10).join(rows)}
"""
    OUT_PATH.write_text(page)
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
